# Generated by Django 6.0.2 on 2026-04-07 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название банка')),
                ('service_name', models.CharField(blank=True, max_length=200, verbose_name='Название сервиса для самозанятых')),
                ('bank_type', models.CharField(choices=[('state', 'Государственный'), ('private', 'Частный'), ('foreign', 'Иностранный')], default='private', max_length=20, verbose_name='Тип банка')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='Номер лицензии ЦБ РФ')),
                ('founded_year', models.IntegerField(blank=True, null=True, verbose_name='Год основания')),
                ('years_existence', models.IntegerField(blank=True, null=True, verbose_name='Лет на рынке')),
                ('branches_count', models.IntegerField(default=0, verbose_name='Количество отделений в НО')),
                ('atms_count', models.IntegerField(default=0, verbose_name='Количество банкоматов в НО')),
                ('financial_rating', models.IntegerField(blank=True, null=True, verbose_name='Финансовый рейтинг (место)')),
                ('public_rating', models.IntegerField(blank=True, null=True, verbose_name='Народный рейтинг (место)')),
                ('avg_customer_rating', models.FloatField(default=0, verbose_name='Средняя оценка клиентов')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон горячей линии')),
                ('website', models.URLField(blank=True, verbose_name='Официальный сайт')),
                ('support_online', models.BooleanField(default=True, verbose_name='Круглосуточная онлайн-поддержка')),
                ('description', models.TextField(blank=True, verbose_name='Описание банка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
                'db_table': 'services_bank',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DBOService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сервиса')),
                ('mobile_app', models.BooleanField(default=False, verbose_name='Мобильное приложение')),
                ('web_cabinet', models.BooleanField(default=False, verbose_name='Веб-кабинет')),
                ('onboarding_speed', models.IntegerField(default=5, verbose_name='Скорость подключения (минут)')),
                ('automatic_checks', models.BooleanField(default=False, verbose_name='Автоматическое формирование чеков')),
                ('cancel_checks', models.BooleanField(default=False, verbose_name='Отмена чеков')),
                ('auto_tax_calculation', models.BooleanField(default=True, verbose_name='Автоматический расчет налога')),
                ('auto_tax_payment', models.BooleanField(default=False, verbose_name='Автоплатеж налога')),
                ('payment_by_phone', models.BooleanField(default=True, verbose_name='Приём переводов по номеру телефона')),
                ('payment_by_qr', models.BooleanField(default=True, verbose_name='Приём переводов по QR-коду')),
                ('payment_by_details', models.BooleanField(default=True, verbose_name='Приём переводов по реквизитам')),
                ('sbp_integration', models.BooleanField(default=True, verbose_name='Поддержка СБП')),
                ('income_statistics', models.BooleanField(default=False, verbose_name='Наличие аналитики доходов')),
                ('limit_control', models.BooleanField(default=False, verbose_name='Контроль лимита дохода')),
                ('two_factor_auth', models.BooleanField(default=False, verbose_name='Двухфакторная аутентификация')),
                ('antifraud_automated', models.BooleanField(default=True, verbose_name='Антифрод-мониторинг')),
                ('auto_logout', models.BooleanField(default=True, verbose_name='Автовыход при бездействии')),
                ('auto_logout_time', models.IntegerField(default=5, verbose_name='Время автовыхода (мин)')),
                ('support_online', models.BooleanField(default=True, verbose_name='Круглосуточная поддержка 24/7')),
                ('international_transfers', models.BooleanField(default=False, verbose_name='Доступны международные переводы')),
                ('international_countries', models.TextField(blank=True, verbose_name='Страны для переводов')),
                ('swift_available', models.BooleanField(default=False, verbose_name='SWIFT переводы')),
                ('monthly_fee_min', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Мин. плата (₽/мес)')),
                ('monthly_fee_max', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Макс. плата (₽/мес)')),
                ('internal_transfer_fee', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Внутрибанк комиссия (%)')),
                ('sbp_transfer_fee', models.DecimalField(decimal_places=2, default=0.5, max_digits=5, verbose_name='СБП комиссия (%)')),
                ('card_transfer_fee', models.DecimalField(decimal_places=2, default=1.5, max_digits=5, verbose_name='По карте комиссия (%)')),
                ('transfer_free_limit', models.IntegerField(default=100000, verbose_name='Бесплатный лимит (₽/мес)')),
                ('cash_withdrawal_free_limit', models.IntegerField(default=100000, verbose_name='Бесплатный лимит снятия (₽/мес)')),
                ('cash_withdrawal_fee', models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='Комиссия за снятие сверх лимита (%)')),
                ('deposit_free_limit', models.CharField(max_length=200, verbose_name='Бесплатный лимит внесения (₽/мес)')),
                ('deposit_fee', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Комиссия за внесение сверх лимита (%)')),
                ('ahp_rating', models.FloatField(default=0, verbose_name='AHP рейтинг')),
                ('saw_rating', models.FloatField(default=0, verbose_name='SAW рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.bank', verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'Сервис ДБО',
                'verbose_name_plural': 'Сервисы ДБО',
                'db_table': 'services_dboservice',
                'ordering': ['-ahp_rating', 'name'],
            },
        ),
    ]
